[Allpix]
log_level = WARNING              
detectors_file = "CMOS_Sensor_geom.conf" 
number_of_events = 5000
root_file =histo_CMOS_paper25um20V.root
[GeometryBuilderGeant4]
log_level = DEBUG

[DepositionGeant4]
physics_list = "FTFP_BERT_EMY"
enable_pai = true
particle_type = pi+              
source_type = "beam"
source_energy = 120GeV
source_position = 0um 0um -200um
beam_size = 20um
beam_direction = 0 0 1
number_of_particles = 1
max_step_length = 1.0um
#log_level = DEBUG
output_plots = 1

[ElectricFieldReader]
model = linear                  
bias_voltage = -20V 
depletion_depth = 25um 
#log_level = DEBUG
#output_plots = 1

[GenericPropagation]
temperature = 293K
timestep_min = 0.5ps
timestep_max = 0.5ns
integration_time = 20ns        
charge_per_step = 5
spatial_precision = 0.1um
#propagate_holes= true
#output_linegraphs = true
#output_linegraphs_collected = true
#output_plots_lines_at_implants = true
#output_plots_step = 100ps
#output_plots_align_pixels = true
#output_plots_use_pixel_units = true
#log_level = DEBUG
output_plots = 1

[SimpleTransfer]
max_depth_distance= 3um
log_level = DEBUG
output_plots = 1

[DefaultDigitizer]            
threshold = 120e 
threshold_smearing=5e
electronics_noise = 10e
#log_level = DEBUG
output_plots = 1


[DetectorHistogrammer]
#log_level = DEBUG
track_resolution = 2um 2um


[ROOTObjectWriter]
file_name = "cmos_paper25um20V.root" 
#[VisualizationGeant4]



